added extract_data function and main function
hgao62/cara_backend_etl pull request #2
Opened 2024-08-27 03:31 UTC by Claire-cpu

developed extract_data function and main function.

2024-08-27 03:40 UTC, hgao62 commented on extract_data.py
> +    """_summary_
please finish doc string

2024-08-27 03:40 UTC, hgao62 commented on main.py
> +    print(google)
remove print statement

2024-08-27 03:41 UTC, hgao62 requested changes
please see my comments

2024-09-02 03:24 UTC, hgao62 commented on extract_data.py
> +    hist = stock_info.history(period='1mo')
please compare the output this function with the expected output in read me file. dataframe output should have these columns

![image](https://github.com/user-attachments/assets/2c23c57b-c4fc-4927-937d-5715188c1855)

2024-09-02 03:24 UTC, hgao62 commented on extract_data.py
> +    stock_info = yf.Ticker(stock)
please compre the output with expected output in read me to make sure they have the columns

![image](https://github.com/user-attachments/assets/bcb4afac-591c-494b-8ccc-22a4dc4aaddf)

2024-09-02 03:24 UTC, hgao62 commented on extract_data.py
> +    """_summary_
please finish doc string

2024-09-02 03:24 UTC, hgao62 commented on extract_data.py
> +    return fx_data
please compare output with expected output columns in read me file. it should have these columns

![image](https://github.com/user-attachments/assets/c59ebb5d-d45d-4b30-b067-37c3038bde63)

2024-09-09 21:18 UTC, hgao62 commented on extract_data.py
> +    return hist
this is your output
![image](https://github.com/user-attachments/assets/2dedb0e9-eb0d-4564-a088-115abbd720d3)

this is the expected output. they don't match. please double check
![image](https://github.com/user-attachments/assets/06e8b5ca-7b26-4760-9de4-d6a99bbf9c49)

2024-09-09 21:18 UTC, hgao62 commented on extract_data.py
> +    # Download the historical FX data
![image](https://github.com/user-attachments/assets/355f7c91-14a7-46eb-98ed-c59eef85c5df)

in your output, Date is output as an index. please change it to a column. Google " how to convert pandas dataframe to a column”

2024-09-09 21:18 UTC, hgao62 commented on extract_data.py
> +    stock_info = yf.Ticker(stock)
output columns still don't match expected output from screenshot

2024-09-09 21:18 UTC, hgao62 commented on extract_data.py
> +        date, open, high, low, close, volumn, dividens, stock
typo in volumn and dividens

2024-09-09 21:18 UTC, hgao62 commented on extract_data.py
> +    """this function should get fiancial metrics given a stock input
typo(fiancial changed to financial)

2024-09-09 21:18 UTC, hgao62 commented on extract_data.py
> +        to_currency (str): currency to covnert to
typo(covnert -> convert)

2024-09-09 21:18 UTC, hgao62 commented on extract_data.py
> +        pd.DataFrame: foreign exhange rates between two currencies by specified time interval
exhange: typo

2024-09-09 21:18 UTC, hgao62 commented on extract_data.py
> +    fx_data.insert(0,'Ticker',ticker)
please refactor it to code below. when you use number such 0, 1,2,3 in our code, it's called magic number(
see stackoverflow)
https://stackoverflow.com/questions/47882/what-are-magic-numbers-and-why-do-some-consider-them-bad 

 it will make code hard to maintian in the future

```python
fx_rates["Ticker"] = fx_rate_ticker
    fx_rates["From Currency"] = from_currency
    fx_rates["To Currency"] = to_currency
    fx_rates = fx_rates.reset_index()
    output_columns = [
        "Date",
        "Ticker",
        "From Currency",
        "To Currency",
        "Open",
        "High",
        "Low",
        "Close",
        "Adj Close",
    ]

    return fx_rates[output_columns]
```

2024-09-10 21:01 UTC, Claire-cpu commented on extract_data.py
> +    return hist
Corrected.

2024-09-10 22:05 UTC, Claire-cpu commented on extract_data.py
> +    # Download the historical FX data
corrected

2024-09-11 02:39 UTC, Claire-cpu commented on extract_data.py
> +        date, open, high, low, close, volumn, dividens, stock
corrected

2024-09-11 03:04 UTC, Claire-cpu commented on extract_data.py
> +    """this function should get fiancial metrics given a stock input
corrected get_news and typo(fiancial changed to financial)

2024-09-11 03:05 UTC, Claire-cpu commented on extract_data.py
> +        to_currency (str): currency to covnert to
Corrected typo(covnert -> convert)

2024-09-11 03:06 UTC, Claire-cpu commented on extract_data.py
> +        pd.DataFrame: foreign exhange rates between two currencies by specified time interval
corrected exhange: typo

2024-09-11 03:25 UTC, Claire-cpu commented on extract_data.py
> +    fx_data.insert(0,'Ticker',ticker)
corrected magical numbers

2024-09-12 01:08 UTC, hgao62 approved these changes

2024-09-12 01:12 UTC, merged